CREATE TABLE IF NOT EXISTS `#__remidials` (
    `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `catid` INT(11) NOT NULL DEFAULT 0,
    `tahun_ajaran` VARCHAR(10) NOT NULL DEFAULT '',
    `nilai_id` INT(10) UNSIGNED NOT NULL,
    `state` TINYINT(4) NOT NULL DEFAULT 0,
    `dosen_id` INT(10) NOT NULL,
    `auth_fakultas` TINYINT(4) UNSIGNED NOT NULL DEFAULT 0,
    `nilai_awal` TINYINT(4) UNSIGNED NOT NULL DEFAULT 0,
    `nilai_remidial` TINYINT(4) NULL DEFAULT NULL,
    `input_by` INT(10) NOT NULL DEFAULT 0,
    `input_date` DATETIME NULL DEFAULT NULL,
    `checked_out` INT(10) UNSIGNED  NOT NULL DEFAULT 0,
	`checked_out_time` 	DATETIME,
	`created_by` INT(10) NULL DEFAULT NULL,
	`created_date` DATETIME	NULL DEFAULT NULL,  	
    `asset_id` INT(10) UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY (`id`),
    CONSTRAINT `rem_nilai` FOREIGN KEY (`nilai_id`) REFERENCES `#__siak_nilai` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `rem_dosen` FOREIGN KEY (`dosen_id`) REFERENCES `#__users` (`id`) ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;